# Generated by Django 5.0.4 on 2024-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='RAM',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_object',
            field=models.ManyToManyField(to='mstore.tag'),
        ),
    ]
