# Generated by Django 5.0.4 on 2024-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0002_alter_product_ram_alter_product_tag_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='RAM',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
