# Generated by Django 5.0.4 on 2024-05-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mstore', '0003_alter_product_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='color_object',
        ),
    ]
